version: "3.9"

services:
  ann:
    restart: always
    profiles: [ann]
    image: ghcr.io/openfoodfacts/robotoff-ann:${TAG}
    ports:
      - 5501:5501
    volumes:
      - ./ann_data:/opt/ann/data
