version: "3.9"

services:
  mongodb:
    image: mongo:4.4
    command: mongod --wiredTigerCacheSizeGB 1.5
    ports:
      - "127.0.0.1:${MONGO_EXPOSE_PORT:-27017}:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - webnet

volumes:
  mongodb_data:
