name: Publish Robotoff ANN Docker image
on:
  push:
    tags:
      - releases/robotoff-ann**

jobs:
  push_to_registry:
    name: Push robotoff-ann Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          path: services/ann
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: openfoodfacts/robotoff-ann
          add_git_labels: true
